jobs:
  - job: test
    variables:
      PYTHON_VERSION: 3.9
    strategy:
      matrix:
        windows-py36:
          IMAGE_NAME: vs2017-win2016
          PYTHON_VERSION: 3.6
          TOXENV: py36
        windows-py38-cover:
          IMAGE_NAME: vs2017-win2016
          PYTHON_VERSION: 3.8
          TOXENV: py38-cover
        windows-integration-certbot:
          IMAGE_NAME: vs2017-win2016
          PYTHON_VERSION: 3.8
          TOXENV: integration-certbot
    pool:
      vmImage: $(IMAGE_NAME)
    steps:
      - template: ../steps/tox-steps.yml
  - job: test_sphinx_builds
    pool:
      vmImage: ubuntu-20.04
    steps:
      - template: ../steps/sphinx-steps.yml
